---
- name: Restart redis
  ansible.builtin.systemd_service:
    name: redis-server
    state: restarted

- name: Restart qdrant
  ansible.builtin.systemd_service:
    name: qdrant
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
